### ISSUE TITLE
Feature Request: Capture image 2 clipboard

### ISSUE THREAD

**Issue by DanielXYZ2000** [Jelmerro/UniCam#1]
It would be great if the shown camera image could be copied just by a double click on the screen. 
The reason for this feature request is, that I use a surface tablet and the Office OneNote version does not have the "insert camera image" command compared to the Cloud OneNote version. 
The idea is just to copy the image from the webcam stream to the clipboad and insert it in any other application.

**Comment by Jelmerro** [comment]
It turned out to be a bit odd to work with the clipboard in Java. But at least on all the computers I have access to it works. It did require a different activation method, since double clicking already activates fullscreen. Holding down the mouse/your finger for over a second now streams the image to your clipboard. I will commit the changes shortly, along with a new release.

**Comment by Jelmerro** [comment]
Fixed in the latest commit. New release is on it's way.

**Comment by DanielXYZ2000** [comment]
Thanks for the very fast implementation - It works very good if I use the C key.  But holding down the finger does not work. It works fine with my trackpad but not if i hold the finger on the screen (semi transparent rectangle rises up)
since full screen is available on the program title bar, maybe a double touch (double click) would be an option again. Or maybe you could make it configurable in the preferences.
BR, & thanks again
